server {
  listen 80;
  server_name localhost 127.0.0.1 123.56.65.79 foodshops.fun;
  server_tokens off;
  keepalive_timeout 5;

  access_log /var/log/nginx/app.log;
  error_log /var/log/nginx/op.log;

  # Nginx 健康检查端点
  location = /nginx-health {
    access_log off;
    return 200 "healthy\n";
    add_header Content-Type text/plain;
  }

  # 配置h5接口代理
  location ~* /h5/(.*) {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://foodshop:3000;
  }
  
  # 配置admin接口代理
  location ~* /admin/(.*) {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://foodshop:3000;
  }	

  # 配置test接口代理
  location ~* /test/(.*) {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://foodshop:3000;
  }

	# 用户端对外主入口
	location / {
    alias /usr/share/nginx/html/hi-user/;
    index src/pages/home/index.html src/pages/home/index.htm;
    try_files $uri $uri/ /src/pages/home/index.html;
	}

	# 用户端user
	location ^~ /ucenter {
    alias /usr/share/nginx/html/hi-user/;
    index src/pages/ucenter/index.html src/pages/ucenter/index.htm;
    try_files $uri $uri/ /src/pages/ucenter/index.html;
	}

	# 用户端order
	location ^~ /order {
    alias /usr/share/nginx/html/hi-user/;
    index src/pages/order/index.html src/pages/order/index.htm;
    try_files $uri $uri/ /src/pages/order/index.html;
	}

	# 用户端登录
	location ^~ /login {
    alias /usr/share/nginx/html/hi-user/;
    index src/pages/login/index.html src/pages/login/index.htm;
    try_files $uri $uri/ /src/pages/login/index.html;
	}

	# admin管理后台
	location /admin-user {
    alias /usr/share/nginx/html/admin-user/;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
	}
}
